server:
  port: 8095

spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5446/jsonb?currentSchema=public
    username: postgres
    password: postgres
